import { useNavigate } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, ChefHat, ChevronRight, Sparkles } from "lucide-react";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { AppChrome } from "@/components/AppChrome";
import { ProductCard } from "@/components/ProductCard";
import { useFreshDash } from "@/components/FreshDashProvider";
import { categories, products, promos, type Product } from "@/data/products";
import { naturalSearch } from "@/services/ai";

export function HomePage(){return <AppChrome><Home/></AppChrome>}
function Home(){const s=useFreshDash();const nav=useNavigate();const [slide,setSlide]=useState(0);const [prompt,setPrompt]=useState("");const [thinking,setThinking]=useState(false);const [ai,setAi]=useState<{intent:string[];products:Product[]}|null>(null);useEffect(()=>{const id=setInterval(()=>setSlide(v=>(v+1)%promos.length),5000);return()=>clearInterval(id)},[]);const ask=async(e:FormEvent)=>{e.preventDefault();if(!prompt.trim())return;setThinking(true);setAi(await naturalSearch(prompt));setThinking(false)};const addAll=(list:Product[])=>list.forEach(p=>p.stock&&s.add(p));return <>
  <div className="mx-auto max-w-[1440px] px-4 py-5 sm:px-6 lg:px-8">
    <section className="grid animate-fade-up gap-4 lg:grid-cols-[1.55fr_.75fr]">
      <div className={`relative min-h-[280px] overflow-hidden rounded-2xl p-7 sm:min-h-[330px] sm:p-10 ${promos[slide]?.tone}`} role="region" aria-roledescription="carousel" aria-label="FreshDash offers">
        <div className="relative z-10 max-w-xl"><p className="text-xs font-extrabold text-primary">{promos[slide]?.eyebrow}</p><h1 className="mt-3 max-w-md text-3xl font-extrabold leading-tight sm:text-5xl">{promos[slide]?.title}</h1><p className="mt-3 text-sm font-medium sm:text-base">{promos[slide]?.copy}</p><Button className="mt-6 rounded-full" onClick={()=>void nav({to:"/browse",search:{q:"deals"}})}>Shop now <ChevronRight/></Button></div>
        <span className="absolute bottom-3 right-4 text-[110px] sm:right-12 sm:text-[160px]" aria-hidden>{promos[slide]?.emoji}</span>
        <div className="absolute bottom-4 left-7 z-10 flex gap-2" aria-label="Choose promotion">{promos.map((_,i)=><button key={i} aria-label={`Promotion ${i+1}`} aria-current={slide===i} onClick={()=>setSlide(i)} className={`h-2 rounded-full transition-all ${slide===i?"w-7 bg-primary":"w-2 bg-foreground/25"}`}/>)}</div>
      </div>
      <form onSubmit={ask} className="relative overflow-hidden rounded-2xl bg-foreground p-[2px] shadow-lift"><div className="flex h-full flex-col rounded-[14px] bg-card p-6"><span className="grid size-12 place-items-center rounded-2xl bg-brand-yellow text-2xl">🥑</span><p className="mt-5 text-xs font-extrabold text-primary">FRESHDASH AI</p><h2 className="mt-2 text-2xl font-extrabold">Tell us what you need</h2><p className="mt-2 text-sm text-muted-foreground">A dish, a diet, or a budget—we'll build the basket.</p><textarea className="mt-5 min-h-24 resize-none rounded-2xl bg-muted p-4 text-sm outline-none focus:ring-2 focus:ring-ring" placeholder="Ingredients for paneer butter masala for 4..." value={prompt} onChange={e=>setPrompt(e.target.value)}/><Button className="mt-3 h-11 rounded-full" disabled={thinking}>{thinking?<><span className="size-4 animate-spin rounded-full border-2 border-primary-foreground/30 border-t-primary-foreground"/>Thinking...</>:<><Sparkles/>Ask FreshDash AI</>}</Button></div></form>
    </section>
    <section className="mt-7"><div className="flex gap-4 overflow-x-auto pb-3 [scrollbar-width:none]">{categories.map(([name,emoji],i)=><button key={name} className="group flex min-w-20 flex-col items-center gap-2" onClick={()=>void nav({to:"/browse",search:{q:name}})}><span className={`grid size-16 place-items-center rounded-full text-3xl transition group-hover:-translate-y-1 ${i===0?"bg-accent ring-2 ring-primary":"bg-card shadow-soft"}`}>{emoji}</span><span className="text-center text-[11px] font-bold leading-4">{name}</span><span className={`h-0.5 rounded-full bg-primary transition-all ${i===0?"w-8":"w-0 group-hover:w-8"}`}/></button>)}</div></section>
    <div className="mt-5 flex items-center justify-between rounded-2xl bg-brand-yellow p-4 sm:p-5"><div className="flex min-w-0 items-center gap-3"><span className="text-3xl">🥛</span><div className="min-w-0"><p className="truncate font-extrabold">Running low on milk?</p><p className="text-xs text-brand-yellow-foreground/75">You usually buy it every 3 days.</p></div></div><Button size="sm" className="shrink-0 rounded-full" onClick={()=>s.add(products[6] ?? products[0]!)}>Add milk</Button></div>
    {ai&&<section className="mt-8 rounded-2xl bg-foreground p-5 text-background sm:p-7"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-brand-yellow">✦ AI MATCH</p><h2 className="mt-1 text-xl font-extrabold">Your smart basket</h2><div className="mt-2 flex flex-wrap gap-2">{ai.intent.map(i=><span className="rounded-full bg-background/10 px-3 py-1 text-xs" key={i}>{i}</span>)}</div></div><Button variant="secondary" className="rounded-full" onClick={()=>addAll(ai.products)}>Add all</Button></div><div className="mt-5 flex gap-3 overflow-x-auto">{ai.products.map(p=><div key={p.id} className="flex min-w-48 items-center gap-3 rounded-xl bg-background/10 p-3"><span className="text-3xl">{p.emoji}</span><p className="text-xs font-bold">{p.name}<span className="block opacity-70">₹{p.price}</span></p></div>)}</div></section>}
    <ProductRail title="Order again" subtitle="Your familiar favourites" list={products.slice(6,16)}/><ProductRail title="Trending near you" subtitle="Popular around Indiranagar" list={products.slice(0,12)}/><ProductRail title="Deals under ₹99" subtitle="Small prices, big joy" list={products.filter(p=>p.price<99).slice(0,12)}/>
    <div className="mt-10 grid gap-4 rounded-2xl bg-soft p-5 md:grid-cols-[1fr_auto] md:items-center"><div><p className="flex items-center gap-2 text-lg font-extrabold"><Sparkles className="text-primary"/>Budget mode</p><p className="mt-1 text-sm text-muted-foreground">Smart swaps keep your basket under target.</p></div><div className="flex items-center gap-3"><span className="text-sm font-bold">₹</span><input aria-label="Grocery budget" type="number" className="h-10 w-24 rounded-full bg-card px-3 text-sm outline-none focus:ring-2 focus:ring-ring" value={s.budget} onChange={e=>s.setBudget(Number(e.target.value))}/><Switch checked={s.budgetMode} onCheckedChange={s.setBudgetMode} aria-label="Toggle budget mode"/></div></div>
    <ProductRail title="Because you like fresh breakfast" subtitle="Picked for you by FreshDash AI" list={products.filter(p=>["Dairy","Bakery","Fruits & Veg"].includes(p.category)).slice(0,12)} ai/>
  </div></>}

function ProductRail({title,subtitle,list,ai=false}:{title:string;subtitle:string;list:Product[];ai?:boolean}){const ref=useRef<HTMLDivElement>(null);return <section className="mt-10 animate-fade-up"><div className="mb-4 flex items-end justify-between"><div><h2 className="flex items-center gap-2 text-xl font-extrabold sm:text-2xl">{ai&&<Sparkles className="text-primary"/>}{title}</h2><p className="mt-1 text-xs text-muted-foreground sm:text-sm">{subtitle}</p></div><div className="hidden gap-2 sm:flex"><Button size="icon" variant="outline" className="rounded-full" aria-label="Scroll left" onClick={()=>ref.current?.scrollBy({left:-600,behavior:"smooth"})}><ArrowLeft/></Button><Button size="icon" variant="outline" className="rounded-full" aria-label="Scroll right" onClick={()=>ref.current?.scrollBy({left:600,behavior:"smooth"})}><ArrowRight/></Button></div></div><div ref={ref} className="flex snap-x gap-3 overflow-x-auto pb-4 [scrollbar-width:none] sm:gap-4">{list.map(p=><ProductCard product={p} compact key={p.id}/>)}</div></section>}